### ISSUE TITLE
(queue/initialize! db-conn) does not work on a clean db

### ISSUE THREAD

**Issue by mindreframer** [wildbit/mysql-queue#1]
it seems that in this function 

``` clojure
(defn initialize!
  "Create required MySQL tables if they don't exist. Returns true."
  [db-conn]
  (queries/create-jobs! db-conn)
  (queries/create-scheduled-jobs! db-conn)
  true)
```

`create-jobs!` should be called after `create-scheduled-jobs!` , because it references scheduled_jobs table. 

cheers!

**Comment by temochka** [comment]
That’s a big one, thanks! Looks like I used a different bootstrap method in tests, so this function wasn’t properly tested. Expect the fix to be included in the next patch release.
